name: Arcology Deckbuilder Releases

on:
  release:
    types: [published]

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: arcology-deckbuilder
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: arcology-deckbuilder-${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
